/**
 * Localized donation paths configured in openfoodfacts-server
 * (conf/nginx/snippets/off.locations-redirects.include).
 */
export const LOCALIZED_DONATE_PATHS: Record<string, string> = {
  aa: "/deeq-open-food-facts",
  ach: "/mi-mot-ki-open-food-facts",
  af: "/skenk-aan-open-food-facts",
  ak: "/kye-open-food-facts",
  am: "/le-open-food-facts-yilegesu",
  ar: "/tabarru-li-open-food-facts",
  as: "/open-food-facts-k-daan-diok",
  ast: "/donar-a-open-food-facts-ast",
  az: "/open-food-facts-iane-edin",
  be: "/akhvyaravats-na-open-food-facts",
  ber: "/efk-i-open-food-facts",
  bg: "/daryavane-na-open-food-facts",
  bm: "/sara-ke-open-food-facts-ye",
  bn: "/open-food-facts-ke-daan-korun",
  bo: "/open-food-facts-la-jinpa-tang",
  br: "/rei-da-open-food-facts",
  bs: "/donirajte-open-food-facts-bs",
  ca: "/dona-a-open-food-facts",
  ce: "/open-food-facts-na-sagla-dalar",
  chr: "/open-food-facts-asquadugv",
  co: "/dona-a-open-food-facts-co",
  crs: "/donn-open-food-facts",
  cs: "/darujte-open-food-facts",
  cv: "/open-food-facts-pa-pulkhasvash",
  cy: "/cyfrannu-at-open-food-facts",
  da: "/doner-til-open-food-facts",
  de: "/spenden",
  el: "/dorea-se-openfoodfacts",
  "en-au": "/donate-to-open-food-facts-au",
  "en-gb": "/donate-to-open-food-facts-gb",
  eo: "/donacu-al-open-food-facts",
  es: "/donar-a-open-food-facts",
  et: "/anneta-open-food-factsile",
  eu: "/eman-open-food-facts-i",
  fa: "/komak-be-open-food-facts",
  fi: "/lahjoita-open-food-factsille",
  fil: "/mag-donate-sa-open-food-facts",
  fo: "/lat-open-food-facts-gavu",
  fr: "/faire-un-don-a-open-food-facts",
  ga: "/tabhair-do-open-food-facts",
  gd: "/thoir-do-open-food-facts",
  gl: "/doar-a-open-food-facts",
  gu: "/open-food-facts-mate-daan-karo",
  ha: "/ba-da-gudunmawa-ga-open-food-facts",
  he: "/truma-le-open-food-facts",
  hi: "/open-food-facts-ko-daan-karein",
  hr: "/donirajte-open-food-facts",
  ht: "/fe-yon-don-ak-open-food-facts",
  hu: "/tamogassa-az-open-food-facts-et",
  hy: "/nviraberel-open-food-facts-in",
  id: "/donasi-ke-open-food-facts",
  ii: "/open-food-facts-bbux-zze",
  is: "/stydja-open-food-facts",
  it: "/dona-a-open-food-facts",
  iu: "/open-food-facts-tunirruti",
  ja: "/kifu",
  jv: "/nyumbang-kanggo-open-food-facts",
  ka: "/shemotsiruloba-open-food-facts-istvis",
  kab: "/seddeq-i-open-food-facts",
  kk: "/open-food-facts-ka-qaiyrym-zhasau",
  km: "/borijak-dl-open-food-facts",
  kmr: "/behs-kiri-open-food-facts",
  "kmr-tr": "/behs-kiri-open-food-facts",
  kn: "/open-food-facts-ge-dana-madi",
  ko: "/gibu",
  ku: "/behs-kiri-open-food-facts",
  kw: "/ri-dhe-open-food-facts",
  ky: "/open-food-facts-ke-kambarkan-tashoo",
  la: "/donare-ad-open-food-facts",
  lb: "/spenden-un-open-food-facts",
  lo: "/borijak-hai-open-food-facts-lo",
  lt: "/paaukokite-open-food-facts",
  lv: "/ziedot-open-food-facts",
  mg: "/hanome-fanampiana-ny-open-food-facts",
  mi: "/koha-ki-open-food-facts",
  ml: "/open-food-facts-inu-sambhavana-cheyyuka",
  mn: "/open-food-facts-t-khandiv-orgokh",
  mr: "/open-food-facts-la-vichari-dya",
  ms: "/derma-kepada-open-food-facts",
  mt: "/taghti-lil-open-food-facts",
  my: "/open-food-facts-tho-hlaudar-par",
  nb: "/doner-til-open-food-facts-no",
  ne: "/open-food-facts-lai-sahayog-garnuhos",
  nl: "/doneer-aan-open-food-facts",
  "nl-be": "/doneer-aan-open-food-facts-be",
  "nl-nl": "/doneer-aan-open-food-facts-nl",
  nn: "/doner-til-open-food-facts-nn",
  no: "/doner-til-open-food-facts-no",
  nr: "/nikela-ku-open-food-facts-nr",
  oc: "/donar-a-open-food-facts-oc",
  or: "/open-food-facts-ku-daana-karantu",
  pa: "/open-food-facts-nu-dan-karo",
  pl: "/przekaz-darowizne-na-open-food-facts",
  pt: "/fazer-um-donativo-ao-open-food-facts",
  "pt-br": "/fazer-uma-doacao-ao-open-food-facts",
  "pt-pt": "/fazer-um-donativo-ao-open-food-facts-pt",
  qu: "/qunay-open-food-facts",
  rm: "/donar-ad-open-food-facts",
  ro: "/doneaza-pentru-open-food-facts",
  ru: "/pozhertvovat-open-food-facts",
  sa: "/open-food-facts-artha-daanam",
  sat: "/open-food-facts-emok",
  sc: "/donare-a-open-food-facts",
  sco: "/gie-tae-open-food-facts",
  sd: "/open-food-facts-khe-dan-diyo",
  sg: "/mu-mbongo-na-open-food-facts",
  si: "/open-food-facts-wethata-aadhaara-karanna",
  sk: "/prispejte-na-open-food-facts",
  sl: "/doniraj-k-open-food-facts",
  sma: "/vedtedh-open-food-facts",
  sn: "/ipai-kutsigira-open-food-facts",
  so: "/ku-deeq-open-food-facts",
  son: "/nooraye-noo-open-food-facts",
  sq: "/dhuroni-per-open-food-facts",
  sr: "/donirajte-open-food-facts-sr",
  "sr-cs": "/donirajte-open-food-facts-sr",
  "sr-rs": "/donirajte-open-food-facts-sr",
  ss: "/nikela-ku-open-food-facts-ss",
  st: "/fana-ka-monehelo-ho-open-food-facts",
  sv: "/donera-till-open-food-facts",
  sw: "/changia-open-food-facts",
  ta: "/open-food-facts-ukku-nankodai-alikkavum",
  te: "/open-food-facts-ku-vihalam-ivvandi",
  tg: "/kuhak-ba-open-food-facts",
  th: "/borichak-hai-open-food-facts",
  ti: "/le-open-food-facts-yilegesu-ti",
  tl: "/mag-donate-sa-open-food-facts",
  tn: "/fana-ka-monehelo-open-food-facts",
  tr: "/open-food-factse-bagista-bulunun",
  ts: "/nyikela-ku-open-food-facts",
  tt: "/open-food-facts-ka-yardam-itu",
  tw: "/kye-open-food-facts-tw",
  ty: "/horoa-no-open-food-facts",
  tzl: "/dunaziun-per-open-food-facts",
  ug: "/open-food-facts-qa-iqane-qilish",
  uk: "/pidtrymaty-open-food-facts",
  ur: "/open-food-facts-ko-atiyah-den",
  uz: "/open-food-facts-ga-ehson-qilish",
  val: "/donar-a-open-food-facts-val",
  ve: "/fha-u-toda-open-food-facts",
  vec: "/dona-a-open-food-facts-vec",
  vi: "/dong-gop-cho-open-food-facts",
  vls: "/stort-aan-open-food-facts",
  wa: "/dijh-po-open-food-facts",
  wo: "/saraxle-open-food-facts",
  xh: "/nikela-ku-open-food-facts-xh",
  yi: "/bayshteyer-tsu-open-food-facts",
  yo: "/se-itoyin-si-open-food-facts",
  zea: "/geef-an-open-food-facts",
  zh: "/juanzhu-open-food-facts",
  "zh-cn": "/juanzhu-open-food-facts",
  "zh-hk": "/juanzhu-open-food-facts-hk",
  "zh-tw": "/juanzeng-dao-open-food-facts",
  zu: "/nikela-ku-open-food-facts",
}

/**
 * Returns the localized donation URL for a given locale, falling back to
 * the world-<locale> subdomain or the default donation URL.
 */
export function getLocalizedDonateUrl(
  rawLocale?: string,
  defaultUrl = "https://world.openfoodfacts.org/donate-to-open-food-facts"
): string {
  const locale = rawLocale?.toLowerCase()
  const baseLocale = locale?.split(/[-_]/)[0]
  if (!locale && !baseLocale) {
    return defaultUrl
  }

  const path =
    (locale && LOCALIZED_DONATE_PATHS[locale]) || (baseLocale && LOCALIZED_DONATE_PATHS[baseLocale])

  if (baseLocale && baseLocale !== "en") {
    return path
      ? `https://world-${baseLocale}.openfoodfacts.org${path}`
      : `https://world-${baseLocale}.openfoodfacts.org/donate-to-open-food-facts`
  }

  return path ? `https://world.openfoodfacts.org${path}` : defaultUrl
}
